<?php
/**
 * GetAiTranslateLanguages200ResponsePerformance
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * GetAiTranslateLanguages200ResponsePerformance Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GetAiTranslateLanguages200ResponsePerformance implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'get_ai_translate_languages_200_response_performance';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'fast_mode_available' => 'bool',
        'batch_translation_available' => 'bool',
        'max_text_length' => 'int',
        'max_batch_size' => 'int',
        'typical_response_time_ms' => '\OpenAPI\Client\Model\GetAiTranslateLanguages200ResponsePerformanceTypicalResponseTimeMs'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'fast_mode_available' => null,
        'batch_translation_available' => null,
        'max_text_length' => null,
        'max_batch_size' => null,
        'typical_response_time_ms' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'fast_mode_available' => false,
        'batch_translation_available' => false,
        'max_text_length' => false,
        'max_batch_size' => false,
        'typical_response_time_ms' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'fast_mode_available' => 'fast_mode_available',
        'batch_translation_available' => 'batch_translation_available',
        'max_text_length' => 'max_text_length',
        'max_batch_size' => 'max_batch_size',
        'typical_response_time_ms' => 'typical_response_time_ms'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'fast_mode_available' => 'setFastModeAvailable',
        'batch_translation_available' => 'setBatchTranslationAvailable',
        'max_text_length' => 'setMaxTextLength',
        'max_batch_size' => 'setMaxBatchSize',
        'typical_response_time_ms' => 'setTypicalResponseTimeMs'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'fast_mode_available' => 'getFastModeAvailable',
        'batch_translation_available' => 'getBatchTranslationAvailable',
        'max_text_length' => 'getMaxTextLength',
        'max_batch_size' => 'getMaxBatchSize',
        'typical_response_time_ms' => 'getTypicalResponseTimeMs'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('fast_mode_available', $data ?? [], null);
        $this->setIfExists('batch_translation_available', $data ?? [], null);
        $this->setIfExists('max_text_length', $data ?? [], null);
        $this->setIfExists('max_batch_size', $data ?? [], null);
        $this->setIfExists('typical_response_time_ms', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets fast_mode_available
     *
     * @return bool|null
     */
    public function getFastModeAvailable()
    {
        return $this->container['fast_mode_available'];
    }

    /**
     * Sets fast_mode_available
     *
     * @param bool|null $fast_mode_available fast_mode_available
     *
     * @return self
     */
    public function setFastModeAvailable($fast_mode_available)
    {
        if (is_null($fast_mode_available)) {
            throw new \InvalidArgumentException('non-nullable fast_mode_available cannot be null');
        }
        $this->container['fast_mode_available'] = $fast_mode_available;

        return $this;
    }

    /**
     * Gets batch_translation_available
     *
     * @return bool|null
     */
    public function getBatchTranslationAvailable()
    {
        return $this->container['batch_translation_available'];
    }

    /**
     * Sets batch_translation_available
     *
     * @param bool|null $batch_translation_available batch_translation_available
     *
     * @return self
     */
    public function setBatchTranslationAvailable($batch_translation_available)
    {
        if (is_null($batch_translation_available)) {
            throw new \InvalidArgumentException('non-nullable batch_translation_available cannot be null');
        }
        $this->container['batch_translation_available'] = $batch_translation_available;

        return $this;
    }

    /**
     * Gets max_text_length
     *
     * @return int|null
     */
    public function getMaxTextLength()
    {
        return $this->container['max_text_length'];
    }

    /**
     * Sets max_text_length
     *
     * @param int|null $max_text_length max_text_length
     *
     * @return self
     */
    public function setMaxTextLength($max_text_length)
    {
        if (is_null($max_text_length)) {
            throw new \InvalidArgumentException('non-nullable max_text_length cannot be null');
        }
        $this->container['max_text_length'] = $max_text_length;

        return $this;
    }

    /**
     * Gets max_batch_size
     *
     * @return int|null
     */
    public function getMaxBatchSize()
    {
        return $this->container['max_batch_size'];
    }

    /**
     * Sets max_batch_size
     *
     * @param int|null $max_batch_size max_batch_size
     *
     * @return self
     */
    public function setMaxBatchSize($max_batch_size)
    {
        if (is_null($max_batch_size)) {
            throw new \InvalidArgumentException('non-nullable max_batch_size cannot be null');
        }
        $this->container['max_batch_size'] = $max_batch_size;

        return $this;
    }

    /**
     * Gets typical_response_time_ms
     *
     * @return \OpenAPI\Client\Model\GetAiTranslateLanguages200ResponsePerformanceTypicalResponseTimeMs|null
     */
    public function getTypicalResponseTimeMs()
    {
        return $this->container['typical_response_time_ms'];
    }

    /**
     * Sets typical_response_time_ms
     *
     * @param \OpenAPI\Client\Model\GetAiTranslateLanguages200ResponsePerformanceTypicalResponseTimeMs|null $typical_response_time_ms typical_response_time_ms
     *
     * @return self
     */
    public function setTypicalResponseTimeMs($typical_response_time_ms)
    {
        if (is_null($typical_response_time_ms)) {
            throw new \InvalidArgumentException('non-nullable typical_response_time_ms cannot be null');
        }
        $this->container['typical_response_time_ms'] = $typical_response_time_ms;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


