<?php
/**
 * GetGithubUser200ResponseActivity
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * UAPI OpenAPI
 *
 * Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * GetGithubUser200ResponseActivity Class Doc Comment
 *
 * @category Class
 * @description 贡献活动数据（需开启 activity&#x3D;true）
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GetGithubUser200ResponseActivity implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'get_github_user_200_response_activity';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'contribution_calendar' => '\OpenAPI\Client\Model\GetGithubUser200ResponseActivityContributionCalendar',
        'from' => 'string',
        'organization' => 'string',
        'scope' => 'string',
        'timeline' => '\OpenAPI\Client\Model\GetGithubUser200ResponseActivityTimelineInner[]',
        'to' => 'string',
        'total_commit_contributions' => 'int',
        'total_contributions' => 'int',
        'total_issue_contributions' => 'int',
        'total_pull_request_contributions' => 'int',
        'total_pull_request_review_contributions' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'contribution_calendar' => null,
        'from' => null,
        'organization' => null,
        'scope' => null,
        'timeline' => null,
        'to' => null,
        'total_commit_contributions' => null,
        'total_contributions' => null,
        'total_issue_contributions' => null,
        'total_pull_request_contributions' => null,
        'total_pull_request_review_contributions' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'contribution_calendar' => false,
        'from' => false,
        'organization' => false,
        'scope' => false,
        'timeline' => false,
        'to' => false,
        'total_commit_contributions' => false,
        'total_contributions' => false,
        'total_issue_contributions' => false,
        'total_pull_request_contributions' => false,
        'total_pull_request_review_contributions' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'contribution_calendar' => 'contribution_calendar',
        'from' => 'from',
        'organization' => 'organization',
        'scope' => 'scope',
        'timeline' => 'timeline',
        'to' => 'to',
        'total_commit_contributions' => 'total_commit_contributions',
        'total_contributions' => 'total_contributions',
        'total_issue_contributions' => 'total_issue_contributions',
        'total_pull_request_contributions' => 'total_pull_request_contributions',
        'total_pull_request_review_contributions' => 'total_pull_request_review_contributions'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'contribution_calendar' => 'setContributionCalendar',
        'from' => 'setFrom',
        'organization' => 'setOrganization',
        'scope' => 'setScope',
        'timeline' => 'setTimeline',
        'to' => 'setTo',
        'total_commit_contributions' => 'setTotalCommitContributions',
        'total_contributions' => 'setTotalContributions',
        'total_issue_contributions' => 'setTotalIssueContributions',
        'total_pull_request_contributions' => 'setTotalPullRequestContributions',
        'total_pull_request_review_contributions' => 'setTotalPullRequestReviewContributions'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'contribution_calendar' => 'getContributionCalendar',
        'from' => 'getFrom',
        'organization' => 'getOrganization',
        'scope' => 'getScope',
        'timeline' => 'getTimeline',
        'to' => 'getTo',
        'total_commit_contributions' => 'getTotalCommitContributions',
        'total_contributions' => 'getTotalContributions',
        'total_issue_contributions' => 'getTotalIssueContributions',
        'total_pull_request_contributions' => 'getTotalPullRequestContributions',
        'total_pull_request_review_contributions' => 'getTotalPullRequestReviewContributions'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('contribution_calendar', $data ?? [], null);
        $this->setIfExists('from', $data ?? [], null);
        $this->setIfExists('organization', $data ?? [], null);
        $this->setIfExists('scope', $data ?? [], null);
        $this->setIfExists('timeline', $data ?? [], null);
        $this->setIfExists('to', $data ?? [], null);
        $this->setIfExists('total_commit_contributions', $data ?? [], null);
        $this->setIfExists('total_contributions', $data ?? [], null);
        $this->setIfExists('total_issue_contributions', $data ?? [], null);
        $this->setIfExists('total_pull_request_contributions', $data ?? [], null);
        $this->setIfExists('total_pull_request_review_contributions', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets contribution_calendar
     *
     * @return \OpenAPI\Client\Model\GetGithubUser200ResponseActivityContributionCalendar|null
     */
    public function getContributionCalendar()
    {
        return $this->container['contribution_calendar'];
    }

    /**
     * Sets contribution_calendar
     *
     * @param \OpenAPI\Client\Model\GetGithubUser200ResponseActivityContributionCalendar|null $contribution_calendar contribution_calendar
     *
     * @return self
     */
    public function setContributionCalendar($contribution_calendar)
    {
        if (is_null($contribution_calendar)) {
            throw new \InvalidArgumentException('non-nullable contribution_calendar cannot be null');
        }
        $this->container['contribution_calendar'] = $contribution_calendar;

        return $this;
    }

    /**
     * Gets from
     *
     * @return string|null
     */
    public function getFrom()
    {
        return $this->container['from'];
    }

    /**
     * Sets from
     *
     * @param string|null $from 统计开始日期。
     *
     * @return self
     */
    public function setFrom($from)
    {
        if (is_null($from)) {
            throw new \InvalidArgumentException('non-nullable from cannot be null');
        }
        $this->container['from'] = $from;

        return $this;
    }

    /**
     * Gets organization
     *
     * @return string|null
     */
    public function getOrganization()
    {
        return $this->container['organization'];
    }

    /**
     * Sets organization
     *
     * @param string|null $organization 按组织过滤时对应的组织登录名。
     *
     * @return self
     */
    public function setOrganization($organization)
    {
        if (is_null($organization)) {
            throw new \InvalidArgumentException('non-nullable organization cannot be null');
        }
        $this->container['organization'] = $organization;

        return $this;
    }

    /**
     * Gets scope
     *
     * @return string|null
     */
    public function getScope()
    {
        return $this->container['scope'];
    }

    /**
     * Sets scope
     *
     * @param string|null $scope 活动统计范围，常见值为 all 或 organization。
     *
     * @return self
     */
    public function setScope($scope)
    {
        if (is_null($scope)) {
            throw new \InvalidArgumentException('non-nullable scope cannot be null');
        }
        $this->container['scope'] = $scope;

        return $this;
    }

    /**
     * Gets timeline
     *
     * @return \OpenAPI\Client\Model\GetGithubUser200ResponseActivityTimelineInner[]|null
     */
    public function getTimeline()
    {
        return $this->container['timeline'];
    }

    /**
     * Sets timeline
     *
     * @param \OpenAPI\Client\Model\GetGithubUser200ResponseActivityTimelineInner[]|null $timeline 按月份聚合后的贡献时间线。
     *
     * @return self
     */
    public function setTimeline($timeline)
    {
        if (is_null($timeline)) {
            throw new \InvalidArgumentException('non-nullable timeline cannot be null');
        }
        $this->container['timeline'] = $timeline;

        return $this;
    }

    /**
     * Gets to
     *
     * @return string|null
     */
    public function getTo()
    {
        return $this->container['to'];
    }

    /**
     * Sets to
     *
     * @param string|null $to 统计结束日期。
     *
     * @return self
     */
    public function setTo($to)
    {
        if (is_null($to)) {
            throw new \InvalidArgumentException('non-nullable to cannot be null');
        }
        $this->container['to'] = $to;

        return $this;
    }

    /**
     * Gets total_commit_contributions
     *
     * @return int|null
     */
    public function getTotalCommitContributions()
    {
        return $this->container['total_commit_contributions'];
    }

    /**
     * Sets total_commit_contributions
     *
     * @param int|null $total_commit_contributions Commit 贡献总数。
     *
     * @return self
     */
    public function setTotalCommitContributions($total_commit_contributions)
    {
        if (is_null($total_commit_contributions)) {
            throw new \InvalidArgumentException('non-nullable total_commit_contributions cannot be null');
        }
        $this->container['total_commit_contributions'] = $total_commit_contributions;

        return $this;
    }

    /**
     * Gets total_contributions
     *
     * @return int|null
     */
    public function getTotalContributions()
    {
        return $this->container['total_contributions'];
    }

    /**
     * Sets total_contributions
     *
     * @param int|null $total_contributions 统计范围内的总贡献数。
     *
     * @return self
     */
    public function setTotalContributions($total_contributions)
    {
        if (is_null($total_contributions)) {
            throw new \InvalidArgumentException('non-nullable total_contributions cannot be null');
        }
        $this->container['total_contributions'] = $total_contributions;

        return $this;
    }

    /**
     * Gets total_issue_contributions
     *
     * @return int|null
     */
    public function getTotalIssueContributions()
    {
        return $this->container['total_issue_contributions'];
    }

    /**
     * Sets total_issue_contributions
     *
     * @param int|null $total_issue_contributions Issue 贡献总数。
     *
     * @return self
     */
    public function setTotalIssueContributions($total_issue_contributions)
    {
        if (is_null($total_issue_contributions)) {
            throw new \InvalidArgumentException('non-nullable total_issue_contributions cannot be null');
        }
        $this->container['total_issue_contributions'] = $total_issue_contributions;

        return $this;
    }

    /**
     * Gets total_pull_request_contributions
     *
     * @return int|null
     */
    public function getTotalPullRequestContributions()
    {
        return $this->container['total_pull_request_contributions'];
    }

    /**
     * Sets total_pull_request_contributions
     *
     * @param int|null $total_pull_request_contributions Pull Request 贡献总数。
     *
     * @return self
     */
    public function setTotalPullRequestContributions($total_pull_request_contributions)
    {
        if (is_null($total_pull_request_contributions)) {
            throw new \InvalidArgumentException('non-nullable total_pull_request_contributions cannot be null');
        }
        $this->container['total_pull_request_contributions'] = $total_pull_request_contributions;

        return $this;
    }

    /**
     * Gets total_pull_request_review_contributions
     *
     * @return int|null
     */
    public function getTotalPullRequestReviewContributions()
    {
        return $this->container['total_pull_request_review_contributions'];
    }

    /**
     * Sets total_pull_request_review_contributions
     *
     * @param int|null $total_pull_request_review_contributions Pull Request Review 贡献总数。
     *
     * @return self
     */
    public function setTotalPullRequestReviewContributions($total_pull_request_review_contributions)
    {
        if (is_null($total_pull_request_review_contributions)) {
            throw new \InvalidArgumentException('non-nullable total_pull_request_review_contributions cannot be null');
        }
        $this->container['total_pull_request_review_contributions'] = $total_pull_request_review_contributions;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


