<?php
/**
 * GetMiscWeather200Response
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * GetMiscWeather200Response Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GetMiscWeather200Response implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'get_misc_weather_200_response';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'province' => 'string',
        'city' => 'string',
        'adcode' => 'string',
        'weather' => 'string',
        'temperature' => 'float',
        'wind_direction' => 'string',
        'wind_power' => 'string',
        'humidity' => 'float',
        'report_time' => 'string',
        'feels_like' => 'float',
        'visibility' => 'float',
        'pressure' => 'float',
        'uv' => 'float',
        'precipitation' => 'float',
        'cloud' => 'float',
        'aqi' => 'float',
        'aqi_level' => 'float',
        'aqi_category' => 'string',
        'aqi_primary' => 'string',
        'air_pollutants' => '\OpenAPI\Client\Model\GetMiscWeather200ResponseAirPollutants',
        'temp_max' => 'float',
        'temp_min' => 'float',
        'forecast' => '\OpenAPI\Client\Model\GetMiscWeather200ResponseForecastInner[]',
        'hourly_forecast' => '\OpenAPI\Client\Model\GetMiscWeather200ResponseHourlyForecastInner[]',
        'minutely_precip' => '\OpenAPI\Client\Model\GetMiscWeather200ResponseMinutelyPrecip',
        'life_indices' => '\OpenAPI\Client\Model\GetMiscWeather200ResponseLifeIndices'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'province' => null,
        'city' => null,
        'adcode' => null,
        'weather' => null,
        'temperature' => null,
        'wind_direction' => null,
        'wind_power' => null,
        'humidity' => null,
        'report_time' => null,
        'feels_like' => null,
        'visibility' => null,
        'pressure' => null,
        'uv' => null,
        'precipitation' => null,
        'cloud' => null,
        'aqi' => null,
        'aqi_level' => null,
        'aqi_category' => null,
        'aqi_primary' => null,
        'air_pollutants' => null,
        'temp_max' => null,
        'temp_min' => null,
        'forecast' => null,
        'hourly_forecast' => null,
        'minutely_precip' => null,
        'life_indices' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'province' => false,
        'city' => false,
        'adcode' => false,
        'weather' => false,
        'temperature' => false,
        'wind_direction' => false,
        'wind_power' => false,
        'humidity' => false,
        'report_time' => false,
        'feels_like' => false,
        'visibility' => false,
        'pressure' => false,
        'uv' => false,
        'precipitation' => false,
        'cloud' => false,
        'aqi' => false,
        'aqi_level' => false,
        'aqi_category' => false,
        'aqi_primary' => false,
        'air_pollutants' => false,
        'temp_max' => false,
        'temp_min' => false,
        'forecast' => false,
        'hourly_forecast' => false,
        'minutely_precip' => false,
        'life_indices' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'province' => 'province',
        'city' => 'city',
        'adcode' => 'adcode',
        'weather' => 'weather',
        'temperature' => 'temperature',
        'wind_direction' => 'wind_direction',
        'wind_power' => 'wind_power',
        'humidity' => 'humidity',
        'report_time' => 'report_time',
        'feels_like' => 'feels_like',
        'visibility' => 'visibility',
        'pressure' => 'pressure',
        'uv' => 'uv',
        'precipitation' => 'precipitation',
        'cloud' => 'cloud',
        'aqi' => 'aqi',
        'aqi_level' => 'aqi_level',
        'aqi_category' => 'aqi_category',
        'aqi_primary' => 'aqi_primary',
        'air_pollutants' => 'air_pollutants',
        'temp_max' => 'temp_max',
        'temp_min' => 'temp_min',
        'forecast' => 'forecast',
        'hourly_forecast' => 'hourly_forecast',
        'minutely_precip' => 'minutely_precip',
        'life_indices' => 'life_indices'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'province' => 'setProvince',
        'city' => 'setCity',
        'adcode' => 'setAdcode',
        'weather' => 'setWeather',
        'temperature' => 'setTemperature',
        'wind_direction' => 'setWindDirection',
        'wind_power' => 'setWindPower',
        'humidity' => 'setHumidity',
        'report_time' => 'setReportTime',
        'feels_like' => 'setFeelsLike',
        'visibility' => 'setVisibility',
        'pressure' => 'setPressure',
        'uv' => 'setUv',
        'precipitation' => 'setPrecipitation',
        'cloud' => 'setCloud',
        'aqi' => 'setAqi',
        'aqi_level' => 'setAqiLevel',
        'aqi_category' => 'setAqiCategory',
        'aqi_primary' => 'setAqiPrimary',
        'air_pollutants' => 'setAirPollutants',
        'temp_max' => 'setTempMax',
        'temp_min' => 'setTempMin',
        'forecast' => 'setForecast',
        'hourly_forecast' => 'setHourlyForecast',
        'minutely_precip' => 'setMinutelyPrecip',
        'life_indices' => 'setLifeIndices'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'province' => 'getProvince',
        'city' => 'getCity',
        'adcode' => 'getAdcode',
        'weather' => 'getWeather',
        'temperature' => 'getTemperature',
        'wind_direction' => 'getWindDirection',
        'wind_power' => 'getWindPower',
        'humidity' => 'getHumidity',
        'report_time' => 'getReportTime',
        'feels_like' => 'getFeelsLike',
        'visibility' => 'getVisibility',
        'pressure' => 'getPressure',
        'uv' => 'getUv',
        'precipitation' => 'getPrecipitation',
        'cloud' => 'getCloud',
        'aqi' => 'getAqi',
        'aqi_level' => 'getAqiLevel',
        'aqi_category' => 'getAqiCategory',
        'aqi_primary' => 'getAqiPrimary',
        'air_pollutants' => 'getAirPollutants',
        'temp_max' => 'getTempMax',
        'temp_min' => 'getTempMin',
        'forecast' => 'getForecast',
        'hourly_forecast' => 'getHourlyForecast',
        'minutely_precip' => 'getMinutelyPrecip',
        'life_indices' => 'getLifeIndices'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('province', $data ?? [], null);
        $this->setIfExists('city', $data ?? [], null);
        $this->setIfExists('adcode', $data ?? [], null);
        $this->setIfExists('weather', $data ?? [], null);
        $this->setIfExists('temperature', $data ?? [], null);
        $this->setIfExists('wind_direction', $data ?? [], null);
        $this->setIfExists('wind_power', $data ?? [], null);
        $this->setIfExists('humidity', $data ?? [], null);
        $this->setIfExists('report_time', $data ?? [], null);
        $this->setIfExists('feels_like', $data ?? [], null);
        $this->setIfExists('visibility', $data ?? [], null);
        $this->setIfExists('pressure', $data ?? [], null);
        $this->setIfExists('uv', $data ?? [], null);
        $this->setIfExists('precipitation', $data ?? [], null);
        $this->setIfExists('cloud', $data ?? [], null);
        $this->setIfExists('aqi', $data ?? [], null);
        $this->setIfExists('aqi_level', $data ?? [], null);
        $this->setIfExists('aqi_category', $data ?? [], null);
        $this->setIfExists('aqi_primary', $data ?? [], null);
        $this->setIfExists('air_pollutants', $data ?? [], null);
        $this->setIfExists('temp_max', $data ?? [], null);
        $this->setIfExists('temp_min', $data ?? [], null);
        $this->setIfExists('forecast', $data ?? [], null);
        $this->setIfExists('hourly_forecast', $data ?? [], null);
        $this->setIfExists('minutely_precip', $data ?? [], null);
        $this->setIfExists('life_indices', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets province
     *
     * @return string|null
     */
    public function getProvince()
    {
        return $this->container['province'];
    }

    /**
     * Sets province
     *
     * @param string|null $province 省份
     *
     * @return self
     */
    public function setProvince($province)
    {
        if (is_null($province)) {
            throw new \InvalidArgumentException('non-nullable province cannot be null');
        }
        $this->container['province'] = $province;

        return $this;
    }

    /**
     * Gets city
     *
     * @return string|null
     */
    public function getCity()
    {
        return $this->container['city'];
    }

    /**
     * Sets city
     *
     * @param string|null $city 城市名
     *
     * @return self
     */
    public function setCity($city)
    {
        if (is_null($city)) {
            throw new \InvalidArgumentException('non-nullable city cannot be null');
        }
        $this->container['city'] = $city;

        return $this;
    }

    /**
     * Gets adcode
     *
     * @return string|null
     */
    public function getAdcode()
    {
        return $this->container['adcode'];
    }

    /**
     * Sets adcode
     *
     * @param string|null $adcode 行政区划代码（部分数据源可能为空）
     *
     * @return self
     */
    public function setAdcode($adcode)
    {
        if (is_null($adcode)) {
            throw new \InvalidArgumentException('non-nullable adcode cannot be null');
        }
        $this->container['adcode'] = $adcode;

        return $this;
    }

    /**
     * Gets weather
     *
     * @return string|null
     */
    public function getWeather()
    {
        return $this->container['weather'];
    }

    /**
     * Sets weather
     *
     * @param string|null $weather 天气状况描述。默认返回中文，传 `lang=en` 时返回英文。非固定枚举。
     *
     * @return self
     */
    public function setWeather($weather)
    {
        if (is_null($weather)) {
            throw new \InvalidArgumentException('non-nullable weather cannot be null');
        }
        $this->container['weather'] = $weather;

        return $this;
    }

    /**
     * Gets temperature
     *
     * @return float|null
     */
    public function getTemperature()
    {
        return $this->container['temperature'];
    }

    /**
     * Sets temperature
     *
     * @param float|null $temperature 当前温度 °C
     *
     * @return self
     */
    public function setTemperature($temperature)
    {
        if (is_null($temperature)) {
            throw new \InvalidArgumentException('non-nullable temperature cannot be null');
        }
        $this->container['temperature'] = $temperature;

        return $this;
    }

    /**
     * Gets wind_direction
     *
     * @return string|null
     */
    public function getWindDirection()
    {
        return $this->container['wind_direction'];
    }

    /**
     * Sets wind_direction
     *
     * @param string|null $wind_direction 风向
     *
     * @return self
     */
    public function setWindDirection($wind_direction)
    {
        if (is_null($wind_direction)) {
            throw new \InvalidArgumentException('non-nullable wind_direction cannot be null');
        }
        $this->container['wind_direction'] = $wind_direction;

        return $this;
    }

    /**
     * Gets wind_power
     *
     * @return string|null
     */
    public function getWindPower()
    {
        return $this->container['wind_power'];
    }

    /**
     * Sets wind_power
     *
     * @param string|null $wind_power 风力等级
     *
     * @return self
     */
    public function setWindPower($wind_power)
    {
        if (is_null($wind_power)) {
            throw new \InvalidArgumentException('non-nullable wind_power cannot be null');
        }
        $this->container['wind_power'] = $wind_power;

        return $this;
    }

    /**
     * Gets humidity
     *
     * @return float|null
     */
    public function getHumidity()
    {
        return $this->container['humidity'];
    }

    /**
     * Sets humidity
     *
     * @param float|null $humidity 相对湿度 %
     *
     * @return self
     */
    public function setHumidity($humidity)
    {
        if (is_null($humidity)) {
            throw new \InvalidArgumentException('non-nullable humidity cannot be null');
        }
        $this->container['humidity'] = $humidity;

        return $this;
    }

    /**
     * Gets report_time
     *
     * @return string|null
     */
    public function getReportTime()
    {
        return $this->container['report_time'];
    }

    /**
     * Sets report_time
     *
     * @param string|null $report_time 数据更新时间
     *
     * @return self
     */
    public function setReportTime($report_time)
    {
        if (is_null($report_time)) {
            throw new \InvalidArgumentException('non-nullable report_time cannot be null');
        }
        $this->container['report_time'] = $report_time;

        return $this;
    }

    /**
     * Gets feels_like
     *
     * @return float|null
     */
    public function getFeelsLike()
    {
        return $this->container['feels_like'];
    }

    /**
     * Sets feels_like
     *
     * @param float|null $feels_like 体感温度 °C（extended=true 时返回）
     *
     * @return self
     */
    public function setFeelsLike($feels_like)
    {
        if (is_null($feels_like)) {
            throw new \InvalidArgumentException('non-nullable feels_like cannot be null');
        }
        $this->container['feels_like'] = $feels_like;

        return $this;
    }

    /**
     * Gets visibility
     *
     * @return float|null
     */
    public function getVisibility()
    {
        return $this->container['visibility'];
    }

    /**
     * Sets visibility
     *
     * @param float|null $visibility 能见度 km（extended=true 时返回）
     *
     * @return self
     */
    public function setVisibility($visibility)
    {
        if (is_null($visibility)) {
            throw new \InvalidArgumentException('non-nullable visibility cannot be null');
        }
        $this->container['visibility'] = $visibility;

        return $this;
    }

    /**
     * Gets pressure
     *
     * @return float|null
     */
    public function getPressure()
    {
        return $this->container['pressure'];
    }

    /**
     * Sets pressure
     *
     * @param float|null $pressure 气压 hPa（extended=true 时返回）
     *
     * @return self
     */
    public function setPressure($pressure)
    {
        if (is_null($pressure)) {
            throw new \InvalidArgumentException('non-nullable pressure cannot be null');
        }
        $this->container['pressure'] = $pressure;

        return $this;
    }

    /**
     * Gets uv
     *
     * @return float|null
     */
    public function getUv()
    {
        return $this->container['uv'];
    }

    /**
     * Sets uv
     *
     * @param float|null $uv 紫外线指数（extended=true 时返回）
     *
     * @return self
     */
    public function setUv($uv)
    {
        if (is_null($uv)) {
            throw new \InvalidArgumentException('non-nullable uv cannot be null');
        }
        $this->container['uv'] = $uv;

        return $this;
    }

    /**
     * Gets precipitation
     *
     * @return float|null
     */
    public function getPrecipitation()
    {
        return $this->container['precipitation'];
    }

    /**
     * Sets precipitation
     *
     * @param float|null $precipitation 当前降水量 mm（extended=true 时返回）
     *
     * @return self
     */
    public function setPrecipitation($precipitation)
    {
        if (is_null($precipitation)) {
            throw new \InvalidArgumentException('non-nullable precipitation cannot be null');
        }
        $this->container['precipitation'] = $precipitation;

        return $this;
    }

    /**
     * Gets cloud
     *
     * @return float|null
     */
    public function getCloud()
    {
        return $this->container['cloud'];
    }

    /**
     * Sets cloud
     *
     * @param float|null $cloud 云量 %（extended=true 时返回）
     *
     * @return self
     */
    public function setCloud($cloud)
    {
        if (is_null($cloud)) {
            throw new \InvalidArgumentException('non-nullable cloud cannot be null');
        }
        $this->container['cloud'] = $cloud;

        return $this;
    }

    /**
     * Gets aqi
     *
     * @return float|null
     */
    public function getAqi()
    {
        return $this->container['aqi'];
    }

    /**
     * Sets aqi
     *
     * @param float|null $aqi 空气质量指数 0-500（extended=true 时返回）
     *
     * @return self
     */
    public function setAqi($aqi)
    {
        if (is_null($aqi)) {
            throw new \InvalidArgumentException('non-nullable aqi cannot be null');
        }
        $this->container['aqi'] = $aqi;

        return $this;
    }

    /**
     * Gets aqi_level
     *
     * @return float|null
     */
    public function getAqiLevel()
    {
        return $this->container['aqi_level'];
    }

    /**
     * Sets aqi_level
     *
     * @param float|null $aqi_level AQI 等级 1-6（extended=true 时返回）
     *
     * @return self
     */
    public function setAqiLevel($aqi_level)
    {
        if (is_null($aqi_level)) {
            throw new \InvalidArgumentException('non-nullable aqi_level cannot be null');
        }
        $this->container['aqi_level'] = $aqi_level;

        return $this;
    }

    /**
     * Gets aqi_category
     *
     * @return string|null
     */
    public function getAqiCategory()
    {
        return $this->container['aqi_category'];
    }

    /**
     * Sets aqi_category
     *
     * @param string|null $aqi_category AQI 等级描述（优/良/轻度污染/中度污染/重度污染/严重污染）（extended=true 时返回）
     *
     * @return self
     */
    public function setAqiCategory($aqi_category)
    {
        if (is_null($aqi_category)) {
            throw new \InvalidArgumentException('non-nullable aqi_category cannot be null');
        }
        $this->container['aqi_category'] = $aqi_category;

        return $this;
    }

    /**
     * Gets aqi_primary
     *
     * @return string|null
     */
    public function getAqiPrimary()
    {
        return $this->container['aqi_primary'];
    }

    /**
     * Sets aqi_primary
     *
     * @param string|null $aqi_primary 主要污染物（如 PM2.5、PM10、O3 等）（extended=true 时返回）
     *
     * @return self
     */
    public function setAqiPrimary($aqi_primary)
    {
        if (is_null($aqi_primary)) {
            throw new \InvalidArgumentException('non-nullable aqi_primary cannot be null');
        }
        $this->container['aqi_primary'] = $aqi_primary;

        return $this;
    }

    /**
     * Gets air_pollutants
     *
     * @return \OpenAPI\Client\Model\GetMiscWeather200ResponseAirPollutants|null
     */
    public function getAirPollutants()
    {
        return $this->container['air_pollutants'];
    }

    /**
     * Sets air_pollutants
     *
     * @param \OpenAPI\Client\Model\GetMiscWeather200ResponseAirPollutants|null $air_pollutants air_pollutants
     *
     * @return self
     */
    public function setAirPollutants($air_pollutants)
    {
        if (is_null($air_pollutants)) {
            throw new \InvalidArgumentException('non-nullable air_pollutants cannot be null');
        }
        $this->container['air_pollutants'] = $air_pollutants;

        return $this;
    }

    /**
     * Gets temp_max
     *
     * @return float|null
     */
    public function getTempMax()
    {
        return $this->container['temp_max'];
    }

    /**
     * Sets temp_max
     *
     * @param float|null $temp_max 当天最高温 °C（forecast=true 时返回）
     *
     * @return self
     */
    public function setTempMax($temp_max)
    {
        if (is_null($temp_max)) {
            throw new \InvalidArgumentException('non-nullable temp_max cannot be null');
        }
        $this->container['temp_max'] = $temp_max;

        return $this;
    }

    /**
     * Gets temp_min
     *
     * @return float|null
     */
    public function getTempMin()
    {
        return $this->container['temp_min'];
    }

    /**
     * Sets temp_min
     *
     * @param float|null $temp_min 当天最低温 °C（forecast=true 时返回）
     *
     * @return self
     */
    public function setTempMin($temp_min)
    {
        if (is_null($temp_min)) {
            throw new \InvalidArgumentException('non-nullable temp_min cannot be null');
        }
        $this->container['temp_min'] = $temp_min;

        return $this;
    }

    /**
     * Gets forecast
     *
     * @return \OpenAPI\Client\Model\GetMiscWeather200ResponseForecastInner[]|null
     */
    public function getForecast()
    {
        return $this->container['forecast'];
    }

    /**
     * Sets forecast
     *
     * @param \OpenAPI\Client\Model\GetMiscWeather200ResponseForecastInner[]|null $forecast 多天天气预报，最多7天（forecast=true 时返回）
     *
     * @return self
     */
    public function setForecast($forecast)
    {
        if (is_null($forecast)) {
            throw new \InvalidArgumentException('non-nullable forecast cannot be null');
        }
        $this->container['forecast'] = $forecast;

        return $this;
    }

    /**
     * Gets hourly_forecast
     *
     * @return \OpenAPI\Client\Model\GetMiscWeather200ResponseHourlyForecastInner[]|null
     */
    public function getHourlyForecast()
    {
        return $this->container['hourly_forecast'];
    }

    /**
     * Sets hourly_forecast
     *
     * @param \OpenAPI\Client\Model\GetMiscWeather200ResponseHourlyForecastInner[]|null $hourly_forecast 逐小时预报，最多24小时（hourly=true 时返回）
     *
     * @return self
     */
    public function setHourlyForecast($hourly_forecast)
    {
        if (is_null($hourly_forecast)) {
            throw new \InvalidArgumentException('non-nullable hourly_forecast cannot be null');
        }
        $this->container['hourly_forecast'] = $hourly_forecast;

        return $this;
    }

    /**
     * Gets minutely_precip
     *
     * @return \OpenAPI\Client\Model\GetMiscWeather200ResponseMinutelyPrecip|null
     */
    public function getMinutelyPrecip()
    {
        return $this->container['minutely_precip'];
    }

    /**
     * Sets minutely_precip
     *
     * @param \OpenAPI\Client\Model\GetMiscWeather200ResponseMinutelyPrecip|null $minutely_precip minutely_precip
     *
     * @return self
     */
    public function setMinutelyPrecip($minutely_precip)
    {
        if (is_null($minutely_precip)) {
            throw new \InvalidArgumentException('non-nullable minutely_precip cannot be null');
        }
        $this->container['minutely_precip'] = $minutely_precip;

        return $this;
    }

    /**
     * Gets life_indices
     *
     * @return \OpenAPI\Client\Model\GetMiscWeather200ResponseLifeIndices|null
     */
    public function getLifeIndices()
    {
        return $this->container['life_indices'];
    }

    /**
     * Sets life_indices
     *
     * @param \OpenAPI\Client\Model\GetMiscWeather200ResponseLifeIndices|null $life_indices life_indices
     *
     * @return self
     */
    public function setLifeIndices($life_indices)
    {
        if (is_null($life_indices)) {
            throw new \InvalidArgumentException('non-nullable life_indices cannot be null');
        }
        $this->container['life_indices'] = $life_indices;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


