<?php
/**
 * GetSayingRandom200Response
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * UAPI OpenAPI
 *
 * Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * GetSayingRandom200Response Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GetSayingRandom200Response implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'get_saying_random_200_response';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'author' => 'string',
        'authorinfo' => '\OpenAPI\Client\Model\RandomAuthorinfo',
        'category' => 'string',
        'content' => 'string',
        'content_length' => 'int',
        'corpus' => 'string',
        'created_at' => 'string',
        'matched_tags' => 'string[]',
        'source' => 'string',
        'uuid' => 'string',
        'current_time' => 'string',
        'date' => 'string',
        'item' => '\OpenAPI\Client\Model\DailyRecommendMomentItem',
        'mode' => 'string',
        'scene' => '\OpenAPI\Client\Model\DailyRecommendMomentScene',
        'seed' => 'string',
        'time_segment' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'author' => null,
        'authorinfo' => null,
        'category' => null,
        'content' => null,
        'content_length' => null,
        'corpus' => null,
        'created_at' => null,
        'matched_tags' => null,
        'source' => null,
        'uuid' => null,
        'current_time' => null,
        'date' => null,
        'item' => null,
        'mode' => null,
        'scene' => null,
        'seed' => null,
        'time_segment' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'author' => false,
        'authorinfo' => false,
        'category' => false,
        'content' => false,
        'content_length' => false,
        'corpus' => false,
        'created_at' => false,
        'matched_tags' => false,
        'source' => false,
        'uuid' => false,
        'current_time' => false,
        'date' => false,
        'item' => false,
        'mode' => false,
        'scene' => false,
        'seed' => false,
        'time_segment' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'author' => 'author',
        'authorinfo' => 'authorinfo',
        'category' => 'category',
        'content' => 'content',
        'content_length' => 'contentLength',
        'corpus' => 'corpus',
        'created_at' => 'createdAt',
        'matched_tags' => 'matchedTags',
        'source' => 'source',
        'uuid' => 'uuid',
        'current_time' => 'currentTime',
        'date' => 'date',
        'item' => 'item',
        'mode' => 'mode',
        'scene' => 'scene',
        'seed' => 'seed',
        'time_segment' => 'timeSegment'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'author' => 'setAuthor',
        'authorinfo' => 'setAuthorinfo',
        'category' => 'setCategory',
        'content' => 'setContent',
        'content_length' => 'setContentLength',
        'corpus' => 'setCorpus',
        'created_at' => 'setCreatedAt',
        'matched_tags' => 'setMatchedTags',
        'source' => 'setSource',
        'uuid' => 'setUuid',
        'current_time' => 'setCurrentTime',
        'date' => 'setDate',
        'item' => 'setItem',
        'mode' => 'setMode',
        'scene' => 'setScene',
        'seed' => 'setSeed',
        'time_segment' => 'setTimeSegment'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'author' => 'getAuthor',
        'authorinfo' => 'getAuthorinfo',
        'category' => 'getCategory',
        'content' => 'getContent',
        'content_length' => 'getContentLength',
        'corpus' => 'getCorpus',
        'created_at' => 'getCreatedAt',
        'matched_tags' => 'getMatchedTags',
        'source' => 'getSource',
        'uuid' => 'getUuid',
        'current_time' => 'getCurrentTime',
        'date' => 'getDate',
        'item' => 'getItem',
        'mode' => 'getMode',
        'scene' => 'getScene',
        'seed' => 'getSeed',
        'time_segment' => 'getTimeSegment'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('author', $data ?? [], null);
        $this->setIfExists('authorinfo', $data ?? [], null);
        $this->setIfExists('category', $data ?? [], null);
        $this->setIfExists('content', $data ?? [], null);
        $this->setIfExists('content_length', $data ?? [], null);
        $this->setIfExists('corpus', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('matched_tags', $data ?? [], null);
        $this->setIfExists('source', $data ?? [], null);
        $this->setIfExists('uuid', $data ?? [], null);
        $this->setIfExists('current_time', $data ?? [], null);
        $this->setIfExists('date', $data ?? [], null);
        $this->setIfExists('item', $data ?? [], null);
        $this->setIfExists('mode', $data ?? [], null);
        $this->setIfExists('scene', $data ?? [], null);
        $this->setIfExists('seed', $data ?? [], null);
        $this->setIfExists('time_segment', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets author
     *
     * @return string|null
     */
    public function getAuthor()
    {
        return $this->container['author'];
    }

    /**
     * Sets author
     *
     * @param string|null $author 作者或说话者。
     *
     * @return self
     */
    public function setAuthor($author)
    {
        if (is_null($author)) {
            throw new \InvalidArgumentException('non-nullable author cannot be null');
        }
        $this->container['author'] = $author;

        return $this;
    }

    /**
     * Gets authorinfo
     *
     * @return \OpenAPI\Client\Model\RandomAuthorinfo|null
     */
    public function getAuthorinfo()
    {
        return $this->container['authorinfo'];
    }

    /**
     * Sets authorinfo
     *
     * @param \OpenAPI\Client\Model\RandomAuthorinfo|null $authorinfo authorinfo
     *
     * @return self
     */
    public function setAuthorinfo($authorinfo)
    {
        if (is_null($authorinfo)) {
            throw new \InvalidArgumentException('non-nullable authorinfo cannot be null');
        }
        $this->container['authorinfo'] = $authorinfo;

        return $this;
    }

    /**
     * Gets category
     *
     * @return string|null
     */
    public function getCategory()
    {
        return $this->container['category'];
    }

    /**
     * Sets category
     *
     * @param string|null $category 语录分类。
     *
     * @return self
     */
    public function setCategory($category)
    {
        if (is_null($category)) {
            throw new \InvalidArgumentException('non-nullable category cannot be null');
        }
        $this->container['category'] = $category;

        return $this;
    }

    /**
     * Gets content
     *
     * @return string|null
     */
    public function getContent()
    {
        return $this->container['content'];
    }

    /**
     * Sets content
     *
     * @param string|null $content 语录正文。
     *
     * @return self
     */
    public function setContent($content)
    {
        if (is_null($content)) {
            throw new \InvalidArgumentException('non-nullable content cannot be null');
        }
        $this->container['content'] = $content;

        return $this;
    }

    /**
     * Gets content_length
     *
     * @return int|null
     */
    public function getContentLength()
    {
        return $this->container['content_length'];
    }

    /**
     * Sets content_length
     *
     * @param int|null $content_length 正文字数。
     *
     * @return self
     */
    public function setContentLength($content_length)
    {
        if (is_null($content_length)) {
            throw new \InvalidArgumentException('non-nullable content_length cannot be null');
        }
        $this->container['content_length'] = $content_length;

        return $this;
    }

    /**
     * Gets corpus
     *
     * @return string|null
     */
    public function getCorpus()
    {
        return $this->container['corpus'];
    }

    /**
     * Sets corpus
     *
     * @param string|null $corpus 所属语料库标识。
     *
     * @return self
     */
    public function setCorpus($corpus)
    {
        if (is_null($corpus)) {
            throw new \InvalidArgumentException('non-nullable corpus cannot be null');
        }
        $this->container['corpus'] = $corpus;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return string|null
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param string|null $created_at 语料入库时间戳（秒），部分语料返回。
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            throw new \InvalidArgumentException('non-nullable created_at cannot be null');
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets matched_tags
     *
     * @return string[]|null
     */
    public function getMatchedTags()
    {
        return $this->container['matched_tags'];
    }

    /**
     * Sets matched_tags
     *
     * @param string[]|null $matched_tags 命中的标签，部分模式返回。
     *
     * @return self
     */
    public function setMatchedTags($matched_tags)
    {
        if (is_null($matched_tags)) {
            throw new \InvalidArgumentException('non-nullable matched_tags cannot be null');
        }
        $this->container['matched_tags'] = $matched_tags;

        return $this;
    }

    /**
     * Gets source
     *
     * @return string|null
     */
    public function getSource()
    {
        return $this->container['source'];
    }

    /**
     * Sets source
     *
     * @param string|null $source 语录出处或来源。
     *
     * @return self
     */
    public function setSource($source)
    {
        if (is_null($source)) {
            throw new \InvalidArgumentException('non-nullable source cannot be null');
        }
        $this->container['source'] = $source;

        return $this;
    }

    /**
     * Gets uuid
     *
     * @return string|null
     */
    public function getUuid()
    {
        return $this->container['uuid'];
    }

    /**
     * Sets uuid
     *
     * @param string|null $uuid 语录唯一标识。
     *
     * @return self
     */
    public function setUuid($uuid)
    {
        if (is_null($uuid)) {
            throw new \InvalidArgumentException('non-nullable uuid cannot be null');
        }
        $this->container['uuid'] = $uuid;

        return $this;
    }

    /**
     * Gets current_time
     *
     * @return string|null
     */
    public function getCurrentTime()
    {
        return $this->container['current_time'];
    }

    /**
     * Sets current_time
     *
     * @param string|null $current_time 仅 moment 模式返回，服务器当前时间，ISO 8601 格式。
     *
     * @return self
     */
    public function setCurrentTime($current_time)
    {
        if (is_null($current_time)) {
            throw new \InvalidArgumentException('non-nullable current_time cannot be null');
        }
        $this->container['current_time'] = $current_time;

        return $this;
    }

    /**
     * Gets date
     *
     * @return string|null
     */
    public function getDate()
    {
        return $this->container['date'];
    }

    /**
     * Sets date
     *
     * @param string|null $date 仅 daily 模式返回，对应日期，格式 YYYY-MM-DD。
     *
     * @return self
     */
    public function setDate($date)
    {
        if (is_null($date)) {
            throw new \InvalidArgumentException('non-nullable date cannot be null');
        }
        $this->container['date'] = $date;

        return $this;
    }

    /**
     * Gets item
     *
     * @return \OpenAPI\Client\Model\DailyRecommendMomentItem|null
     */
    public function getItem()
    {
        return $this->container['item'];
    }

    /**
     * Sets item
     *
     * @param \OpenAPI\Client\Model\DailyRecommendMomentItem|null $item item
     *
     * @return self
     */
    public function setItem($item)
    {
        if (is_null($item)) {
            throw new \InvalidArgumentException('non-nullable item cannot be null');
        }
        $this->container['item'] = $item;

        return $this;
    }

    /**
     * Gets mode
     *
     * @return string|null
     */
    public function getMode()
    {
        return $this->container['mode'];
    }

    /**
     * Sets mode
     *
     * @param string|null $mode 当前运行模式。
     *
     * @return self
     */
    public function setMode($mode)
    {
        if (is_null($mode)) {
            throw new \InvalidArgumentException('non-nullable mode cannot be null');
        }
        $this->container['mode'] = $mode;

        return $this;
    }

    /**
     * Gets scene
     *
     * @return \OpenAPI\Client\Model\DailyRecommendMomentScene|null
     */
    public function getScene()
    {
        return $this->container['scene'];
    }

    /**
     * Sets scene
     *
     * @param \OpenAPI\Client\Model\DailyRecommendMomentScene|null $scene scene
     *
     * @return self
     */
    public function setScene($scene)
    {
        if (is_null($scene)) {
            throw new \InvalidArgumentException('non-nullable scene cannot be null');
        }
        $this->container['scene'] = $scene;

        return $this;
    }

    /**
     * Gets seed
     *
     * @return string|null
     */
    public function getSeed()
    {
        return $this->container['seed'];
    }

    /**
     * Sets seed
     *
     * @param string|null $seed 当次结果的确定性种子。
     *
     * @return self
     */
    public function setSeed($seed)
    {
        if (is_null($seed)) {
            throw new \InvalidArgumentException('non-nullable seed cannot be null');
        }
        $this->container['seed'] = $seed;

        return $this;
    }

    /**
     * Gets time_segment
     *
     * @return string|null
     */
    public function getTimeSegment()
    {
        return $this->container['time_segment'];
    }

    /**
     * Sets time_segment
     *
     * @param string|null $time_segment 仅 moment 模式返回，命中的时段标识。
     *
     * @return self
     */
    public function setTimeSegment($time_segment)
    {
        if (is_null($time_segment)) {
            throw new \InvalidArgumentException('non-nullable time_segment cannot be null');
        }
        $this->container['time_segment'] = $time_segment;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


