<?php
/**
 * GetSocialBilibiliUserinfo200Response
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * GetSocialBilibiliUserinfo200Response Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GetSocialBilibiliUserinfo200Response implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'get_social_bilibili_userinfo_200_response';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'mid' => 'int',
        'name' => 'string',
        'sex' => 'string',
        'face' => 'string',
        'sign' => 'string',
        'level' => 'int',
        'birthday' => 'string',
        'vip_type' => 'int',
        'vip_status' => 'int',
        'following' => 'int',
        'follower' => 'int',
        'archive_count' => 'int',
        'article_count' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'mid' => null,
        'name' => null,
        'sex' => null,
        'face' => null,
        'sign' => null,
        'level' => null,
        'birthday' => null,
        'vip_type' => null,
        'vip_status' => null,
        'following' => null,
        'follower' => null,
        'archive_count' => null,
        'article_count' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'mid' => false,
        'name' => false,
        'sex' => false,
        'face' => false,
        'sign' => false,
        'level' => false,
        'birthday' => false,
        'vip_type' => false,
        'vip_status' => false,
        'following' => false,
        'follower' => false,
        'archive_count' => false,
        'article_count' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'mid' => 'mid',
        'name' => 'name',
        'sex' => 'sex',
        'face' => 'face',
        'sign' => 'sign',
        'level' => 'level',
        'birthday' => 'birthday',
        'vip_type' => 'vip_type',
        'vip_status' => 'vip_status',
        'following' => 'following',
        'follower' => 'follower',
        'archive_count' => 'archive_count',
        'article_count' => 'article_count'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'mid' => 'setMid',
        'name' => 'setName',
        'sex' => 'setSex',
        'face' => 'setFace',
        'sign' => 'setSign',
        'level' => 'setLevel',
        'birthday' => 'setBirthday',
        'vip_type' => 'setVipType',
        'vip_status' => 'setVipStatus',
        'following' => 'setFollowing',
        'follower' => 'setFollower',
        'archive_count' => 'setArchiveCount',
        'article_count' => 'setArticleCount'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'mid' => 'getMid',
        'name' => 'getName',
        'sex' => 'getSex',
        'face' => 'getFace',
        'sign' => 'getSign',
        'level' => 'getLevel',
        'birthday' => 'getBirthday',
        'vip_type' => 'getVipType',
        'vip_status' => 'getVipStatus',
        'following' => 'getFollowing',
        'follower' => 'getFollower',
        'archive_count' => 'getArchiveCount',
        'article_count' => 'getArticleCount'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('mid', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('sex', $data ?? [], null);
        $this->setIfExists('face', $data ?? [], null);
        $this->setIfExists('sign', $data ?? [], null);
        $this->setIfExists('level', $data ?? [], null);
        $this->setIfExists('birthday', $data ?? [], null);
        $this->setIfExists('vip_type', $data ?? [], null);
        $this->setIfExists('vip_status', $data ?? [], null);
        $this->setIfExists('following', $data ?? [], null);
        $this->setIfExists('follower', $data ?? [], null);
        $this->setIfExists('archive_count', $data ?? [], null);
        $this->setIfExists('article_count', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets mid
     *
     * @return int|null
     */
    public function getMid()
    {
        return $this->container['mid'];
    }

    /**
     * Sets mid
     *
     * @param int|null $mid mid
     *
     * @return self
     */
    public function setMid($mid)
    {
        if (is_null($mid)) {
            throw new \InvalidArgumentException('non-nullable mid cannot be null');
        }
        $this->container['mid'] = $mid;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets sex
     *
     * @return string|null
     */
    public function getSex()
    {
        return $this->container['sex'];
    }

    /**
     * Sets sex
     *
     * @param string|null $sex sex
     *
     * @return self
     */
    public function setSex($sex)
    {
        if (is_null($sex)) {
            throw new \InvalidArgumentException('non-nullable sex cannot be null');
        }
        $this->container['sex'] = $sex;

        return $this;
    }

    /**
     * Gets face
     *
     * @return string|null
     */
    public function getFace()
    {
        return $this->container['face'];
    }

    /**
     * Sets face
     *
     * @param string|null $face face
     *
     * @return self
     */
    public function setFace($face)
    {
        if (is_null($face)) {
            throw new \InvalidArgumentException('non-nullable face cannot be null');
        }
        $this->container['face'] = $face;

        return $this;
    }

    /**
     * Gets sign
     *
     * @return string|null
     */
    public function getSign()
    {
        return $this->container['sign'];
    }

    /**
     * Sets sign
     *
     * @param string|null $sign sign
     *
     * @return self
     */
    public function setSign($sign)
    {
        if (is_null($sign)) {
            throw new \InvalidArgumentException('non-nullable sign cannot be null');
        }
        $this->container['sign'] = $sign;

        return $this;
    }

    /**
     * Gets level
     *
     * @return int|null
     */
    public function getLevel()
    {
        return $this->container['level'];
    }

    /**
     * Sets level
     *
     * @param int|null $level level
     *
     * @return self
     */
    public function setLevel($level)
    {
        if (is_null($level)) {
            throw new \InvalidArgumentException('non-nullable level cannot be null');
        }
        $this->container['level'] = $level;

        return $this;
    }

    /**
     * Gets birthday
     *
     * @return string|null
     */
    public function getBirthday()
    {
        return $this->container['birthday'];
    }

    /**
     * Sets birthday
     *
     * @param string|null $birthday birthday
     *
     * @return self
     */
    public function setBirthday($birthday)
    {
        if (is_null($birthday)) {
            throw new \InvalidArgumentException('non-nullable birthday cannot be null');
        }
        $this->container['birthday'] = $birthday;

        return $this;
    }

    /**
     * Gets vip_type
     *
     * @return int|null
     */
    public function getVipType()
    {
        return $this->container['vip_type'];
    }

    /**
     * Sets vip_type
     *
     * @param int|null $vip_type vip_type
     *
     * @return self
     */
    public function setVipType($vip_type)
    {
        if (is_null($vip_type)) {
            throw new \InvalidArgumentException('non-nullable vip_type cannot be null');
        }
        $this->container['vip_type'] = $vip_type;

        return $this;
    }

    /**
     * Gets vip_status
     *
     * @return int|null
     */
    public function getVipStatus()
    {
        return $this->container['vip_status'];
    }

    /**
     * Sets vip_status
     *
     * @param int|null $vip_status vip_status
     *
     * @return self
     */
    public function setVipStatus($vip_status)
    {
        if (is_null($vip_status)) {
            throw new \InvalidArgumentException('non-nullable vip_status cannot be null');
        }
        $this->container['vip_status'] = $vip_status;

        return $this;
    }

    /**
     * Gets following
     *
     * @return int|null
     */
    public function getFollowing()
    {
        return $this->container['following'];
    }

    /**
     * Sets following
     *
     * @param int|null $following following
     *
     * @return self
     */
    public function setFollowing($following)
    {
        if (is_null($following)) {
            throw new \InvalidArgumentException('non-nullable following cannot be null');
        }
        $this->container['following'] = $following;

        return $this;
    }

    /**
     * Gets follower
     *
     * @return int|null
     */
    public function getFollower()
    {
        return $this->container['follower'];
    }

    /**
     * Sets follower
     *
     * @param int|null $follower follower
     *
     * @return self
     */
    public function setFollower($follower)
    {
        if (is_null($follower)) {
            throw new \InvalidArgumentException('non-nullable follower cannot be null');
        }
        $this->container['follower'] = $follower;

        return $this;
    }

    /**
     * Gets archive_count
     *
     * @return int|null
     */
    public function getArchiveCount()
    {
        return $this->container['archive_count'];
    }

    /**
     * Sets archive_count
     *
     * @param int|null $archive_count archive_count
     *
     * @return self
     */
    public function setArchiveCount($archive_count)
    {
        if (is_null($archive_count)) {
            throw new \InvalidArgumentException('non-nullable archive_count cannot be null');
        }
        $this->container['archive_count'] = $archive_count;

        return $this;
    }

    /**
     * Gets article_count
     *
     * @return int|null
     */
    public function getArticleCount()
    {
        return $this->container['article_count'];
    }

    /**
     * Sets article_count
     *
     * @param int|null $article_count article_count
     *
     * @return self
     */
    public function setArticleCount($article_count)
    {
        if (is_null($article_count)) {
            throw new \InvalidArgumentException('non-nullable article_count cannot be null');
        }
        $this->container['article_count'] = $article_count;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


