<?php
/**
 * GetSocialBilibiliReplies200ResponseRepliesInner
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * GetSocialBilibiliReplies200ResponseRepliesInner Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GetSocialBilibiliReplies200ResponseRepliesInner implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'get_social_bilibili_replies_200_response_replies_inner';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'rpid' => 'float',
        'oid' => 'float',
        'mid' => 'float',
        'root' => 'float',
        'parent' => 'float',
        'count' => 'float',
        'ctime' => 'float',
        'like' => 'float',
        'member' => '\OpenAPI\Client\Model\GetSocialBilibiliReplies200ResponseRepliesInnerMember',
        'content' => '\OpenAPI\Client\Model\GetSocialBilibiliReplies200ResponseRepliesInnerContent',
        'replies' => 'object[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'rpid' => null,
        'oid' => null,
        'mid' => null,
        'root' => null,
        'parent' => null,
        'count' => null,
        'ctime' => null,
        'like' => null,
        'member' => null,
        'content' => null,
        'replies' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'rpid' => false,
        'oid' => false,
        'mid' => false,
        'root' => false,
        'parent' => false,
        'count' => false,
        'ctime' => false,
        'like' => false,
        'member' => false,
        'content' => false,
        'replies' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'rpid' => 'rpid',
        'oid' => 'oid',
        'mid' => 'mid',
        'root' => 'root',
        'parent' => 'parent',
        'count' => 'count',
        'ctime' => 'ctime',
        'like' => 'like',
        'member' => 'member',
        'content' => 'content',
        'replies' => 'replies'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'rpid' => 'setRpid',
        'oid' => 'setOid',
        'mid' => 'setMid',
        'root' => 'setRoot',
        'parent' => 'setParent',
        'count' => 'setCount',
        'ctime' => 'setCtime',
        'like' => 'setLike',
        'member' => 'setMember',
        'content' => 'setContent',
        'replies' => 'setReplies'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'rpid' => 'getRpid',
        'oid' => 'getOid',
        'mid' => 'getMid',
        'root' => 'getRoot',
        'parent' => 'getParent',
        'count' => 'getCount',
        'ctime' => 'getCtime',
        'like' => 'getLike',
        'member' => 'getMember',
        'content' => 'getContent',
        'replies' => 'getReplies'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('rpid', $data ?? [], null);
        $this->setIfExists('oid', $data ?? [], null);
        $this->setIfExists('mid', $data ?? [], null);
        $this->setIfExists('root', $data ?? [], null);
        $this->setIfExists('parent', $data ?? [], null);
        $this->setIfExists('count', $data ?? [], null);
        $this->setIfExists('ctime', $data ?? [], null);
        $this->setIfExists('like', $data ?? [], null);
        $this->setIfExists('member', $data ?? [], null);
        $this->setIfExists('content', $data ?? [], null);
        $this->setIfExists('replies', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets rpid
     *
     * @return float|null
     */
    public function getRpid()
    {
        return $this->container['rpid'];
    }

    /**
     * Sets rpid
     *
     * @param float|null $rpid 评论的唯一ID (Reply ID)。
     *
     * @return self
     */
    public function setRpid($rpid)
    {
        if (is_null($rpid)) {
            throw new \InvalidArgumentException('non-nullable rpid cannot be null');
        }
        $this->container['rpid'] = $rpid;

        return $this;
    }

    /**
     * Gets oid
     *
     * @return float|null
     */
    public function getOid()
    {
        return $this->container['oid'];
    }

    /**
     * Sets oid
     *
     * @param float|null $oid 评论区对象ID，即视频的aid。
     *
     * @return self
     */
    public function setOid($oid)
    {
        if (is_null($oid)) {
            throw new \InvalidArgumentException('non-nullable oid cannot be null');
        }
        $this->container['oid'] = $oid;

        return $this;
    }

    /**
     * Gets mid
     *
     * @return float|null
     */
    public function getMid()
    {
        return $this->container['mid'];
    }

    /**
     * Sets mid
     *
     * @param float|null $mid 发表评论的用户的mid。
     *
     * @return self
     */
    public function setMid($mid)
    {
        if (is_null($mid)) {
            throw new \InvalidArgumentException('non-nullable mid cannot be null');
        }
        $this->container['mid'] = $mid;

        return $this;
    }

    /**
     * Gets root
     *
     * @return float|null
     */
    public function getRoot()
    {
        return $this->container['root'];
    }

    /**
     * Sets root
     *
     * @param float|null $root 根评论的rpid。如果为0，表示这条评论是根评论。
     *
     * @return self
     */
    public function setRoot($root)
    {
        if (is_null($root)) {
            throw new \InvalidArgumentException('non-nullable root cannot be null');
        }
        $this->container['root'] = $root;

        return $this;
    }

    /**
     * Gets parent
     *
     * @return float|null
     */
    public function getParent()
    {
        return $this->container['parent'];
    }

    /**
     * Sets parent
     *
     * @param float|null $parent 回复的父级评论的rpid。如果为0，表示是根评论。
     *
     * @return self
     */
    public function setParent($parent)
    {
        if (is_null($parent)) {
            throw new \InvalidArgumentException('non-nullable parent cannot be null');
        }
        $this->container['parent'] = $parent;

        return $this;
    }

    /**
     * Gets count
     *
     * @return float|null
     */
    public function getCount()
    {
        return $this->container['count'];
    }

    /**
     * Sets count
     *
     * @param float|null $count 这条评论下的回复（楼中楼）数量。
     *
     * @return self
     */
    public function setCount($count)
    {
        if (is_null($count)) {
            throw new \InvalidArgumentException('non-nullable count cannot be null');
        }
        $this->container['count'] = $count;

        return $this;
    }

    /**
     * Gets ctime
     *
     * @return float|null
     */
    public function getCtime()
    {
        return $this->container['ctime'];
    }

    /**
     * Sets ctime
     *
     * @param float|null $ctime 评论发送时间的Unix时间戳（秒）。
     *
     * @return self
     */
    public function setCtime($ctime)
    {
        if (is_null($ctime)) {
            throw new \InvalidArgumentException('non-nullable ctime cannot be null');
        }
        $this->container['ctime'] = $ctime;

        return $this;
    }

    /**
     * Gets like
     *
     * @return float|null
     */
    public function getLike()
    {
        return $this->container['like'];
    }

    /**
     * Sets like
     *
     * @param float|null $like 该评论获得的点赞数。
     *
     * @return self
     */
    public function setLike($like)
    {
        if (is_null($like)) {
            throw new \InvalidArgumentException('non-nullable like cannot be null');
        }
        $this->container['like'] = $like;

        return $this;
    }

    /**
     * Gets member
     *
     * @return \OpenAPI\Client\Model\GetSocialBilibiliReplies200ResponseRepliesInnerMember|null
     */
    public function getMember()
    {
        return $this->container['member'];
    }

    /**
     * Sets member
     *
     * @param \OpenAPI\Client\Model\GetSocialBilibiliReplies200ResponseRepliesInnerMember|null $member member
     *
     * @return self
     */
    public function setMember($member)
    {
        if (is_null($member)) {
            throw new \InvalidArgumentException('non-nullable member cannot be null');
        }
        $this->container['member'] = $member;

        return $this;
    }

    /**
     * Gets content
     *
     * @return \OpenAPI\Client\Model\GetSocialBilibiliReplies200ResponseRepliesInnerContent|null
     */
    public function getContent()
    {
        return $this->container['content'];
    }

    /**
     * Sets content
     *
     * @param \OpenAPI\Client\Model\GetSocialBilibiliReplies200ResponseRepliesInnerContent|null $content content
     *
     * @return self
     */
    public function setContent($content)
    {
        if (is_null($content)) {
            throw new \InvalidArgumentException('non-nullable content cannot be null');
        }
        $this->container['content'] = $content;

        return $this;
    }

    /**
     * Gets replies
     *
     * @return object[]|null
     */
    public function getReplies()
    {
        return $this->container['replies'];
    }

    /**
     * Sets replies
     *
     * @param object[]|null $replies 楼中楼回复列表。结构与顶层评论对象一致，但通常此数组为空，需要单独请求。
     *
     * @return self
     */
    public function setReplies($replies)
    {
        if (is_null($replies)) {
            throw new \InvalidArgumentException('non-nullable replies cannot be null');
        }
        $this->container['replies'] = $replies;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


