<?php
/**
 * PostImageOcr200Response
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * UAPI OpenAPI
 *
 * Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * PostImageOcr200Response Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PostImageOcr200Response implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'post_image_ocr_200_response';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'blocks' => 'object[]',
        'image' => 'object',
        'lines' => 'object[]',
        'markdown' => 'string',
        'need_location' => 'bool',
        'pages' => 'object[]',
        'plain_text' => 'string',
        'raw' => 'object',
        'summary' => 'object',
        'text' => 'string',
        'timing' => 'object',
        'words_result' => '\OpenAPI\Client\Model\PostImageOcr200ResponseWordsResultInner[]',
        'words_result_num' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'blocks' => null,
        'image' => null,
        'lines' => null,
        'markdown' => null,
        'need_location' => null,
        'pages' => null,
        'plain_text' => null,
        'raw' => null,
        'summary' => null,
        'text' => null,
        'timing' => null,
        'words_result' => null,
        'words_result_num' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'blocks' => false,
        'image' => false,
        'lines' => false,
        'markdown' => false,
        'need_location' => false,
        'pages' => false,
        'plain_text' => false,
        'raw' => false,
        'summary' => false,
        'text' => false,
        'timing' => false,
        'words_result' => false,
        'words_result_num' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'blocks' => 'blocks',
        'image' => 'image',
        'lines' => 'lines',
        'markdown' => 'markdown',
        'need_location' => 'need_location',
        'pages' => 'pages',
        'plain_text' => 'plain_text',
        'raw' => 'raw',
        'summary' => 'summary',
        'text' => 'text',
        'timing' => 'timing',
        'words_result' => 'words_result',
        'words_result_num' => 'words_result_num'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'blocks' => 'setBlocks',
        'image' => 'setImage',
        'lines' => 'setLines',
        'markdown' => 'setMarkdown',
        'need_location' => 'setNeedLocation',
        'pages' => 'setPages',
        'plain_text' => 'setPlainText',
        'raw' => 'setRaw',
        'summary' => 'setSummary',
        'text' => 'setText',
        'timing' => 'setTiming',
        'words_result' => 'setWordsResult',
        'words_result_num' => 'setWordsResultNum'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'blocks' => 'getBlocks',
        'image' => 'getImage',
        'lines' => 'getLines',
        'markdown' => 'getMarkdown',
        'need_location' => 'getNeedLocation',
        'pages' => 'getPages',
        'plain_text' => 'getPlainText',
        'raw' => 'getRaw',
        'summary' => 'getSummary',
        'text' => 'getText',
        'timing' => 'getTiming',
        'words_result' => 'getWordsResult',
        'words_result_num' => 'getWordsResultNum'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('blocks', $data ?? [], null);
        $this->setIfExists('image', $data ?? [], null);
        $this->setIfExists('lines', $data ?? [], null);
        $this->setIfExists('markdown', $data ?? [], null);
        $this->setIfExists('need_location', $data ?? [], null);
        $this->setIfExists('pages', $data ?? [], null);
        $this->setIfExists('plain_text', $data ?? [], null);
        $this->setIfExists('raw', $data ?? [], null);
        $this->setIfExists('summary', $data ?? [], null);
        $this->setIfExists('text', $data ?? [], null);
        $this->setIfExists('timing', $data ?? [], null);
        $this->setIfExists('words_result', $data ?? [], null);
        $this->setIfExists('words_result_num', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets blocks
     *
     * @return object[]|null
     */
    public function getBlocks()
    {
        return $this->container['blocks'];
    }

    /**
     * Sets blocks
     *
     * @param object[]|null $blocks 按块组织的详细识别结果。
     *
     * @return self
     */
    public function setBlocks($blocks)
    {
        if (is_null($blocks)) {
            throw new \InvalidArgumentException('non-nullable blocks cannot be null');
        }
        $this->container['blocks'] = $blocks;

        return $this;
    }

    /**
     * Gets image
     *
     * @return object|null
     */
    public function getImage()
    {
        return $this->container['image'];
    }

    /**
     * Sets image
     *
     * @param object|null $image 图片本身的基础信息。
     *
     * @return self
     */
    public function setImage($image)
    {
        if (is_null($image)) {
            throw new \InvalidArgumentException('non-nullable image cannot be null');
        }
        $this->container['image'] = $image;

        return $this;
    }

    /**
     * Gets lines
     *
     * @return object[]|null
     */
    public function getLines()
    {
        return $this->container['lines'];
    }

    /**
     * Sets lines
     *
     * @param object[]|null $lines 按行组织的详细识别结果。
     *
     * @return self
     */
    public function setLines($lines)
    {
        if (is_null($lines)) {
            throw new \InvalidArgumentException('non-nullable lines cannot be null');
        }
        $this->container['lines'] = $lines;

        return $this;
    }

    /**
     * Gets markdown
     *
     * @return string|null
     */
    public function getMarkdown()
    {
        return $this->container['markdown'];
    }

    /**
     * Sets markdown
     *
     * @param string|null $markdown 根据图片中的标题、段落和表格整理出的 Markdown 文本。只有在 `return_markdown=true` 时才会返回。
     *
     * @return self
     */
    public function setMarkdown($markdown)
    {
        if (is_null($markdown)) {
            throw new \InvalidArgumentException('non-nullable markdown cannot be null');
        }
        $this->container['markdown'] = $markdown;

        return $this;
    }

    /**
     * Gets need_location
     *
     * @return bool|null
     */
    public function getNeedLocation()
    {
        return $this->container['need_location'];
    }

    /**
     * Sets need_location
     *
     * @param bool|null $need_location 本次响应是否包含坐标信息。
     *
     * @return self
     */
    public function setNeedLocation($need_location)
    {
        if (is_null($need_location)) {
            throw new \InvalidArgumentException('non-nullable need_location cannot be null');
        }
        $this->container['need_location'] = $need_location;

        return $this;
    }

    /**
     * Gets pages
     *
     * @return object[]|null
     */
    public function getPages()
    {
        return $this->container['pages'];
    }

    /**
     * Sets pages
     *
     * @param object[]|null $pages 按页组织的详细识别结果。
     *
     * @return self
     */
    public function setPages($pages)
    {
        if (is_null($pages)) {
            throw new \InvalidArgumentException('non-nullable pages cannot be null');
        }
        $this->container['pages'] = $pages;

        return $this;
    }

    /**
     * Gets plain_text
     *
     * @return string|null
     */
    public function getPlainText()
    {
        return $this->container['plain_text'];
    }

    /**
     * Sets plain_text
     *
     * @param string|null $plain_text 纯文本结果，适合做搜索、索引或直接展示。
     *
     * @return self
     */
    public function setPlainText($plain_text)
    {
        if (is_null($plain_text)) {
            throw new \InvalidArgumentException('non-nullable plain_text cannot be null');
        }
        $this->container['plain_text'] = $plain_text;

        return $this;
    }

    /**
     * Gets raw
     *
     * @return object|null
     */
    public function getRaw()
    {
        return $this->container['raw'];
    }

    /**
     * Sets raw
     *
     * @param object|null $raw 补充识别结果对象，适合需要继续解析更多细节字段的场景。
     *
     * @return self
     */
    public function setRaw($raw)
    {
        if (is_null($raw)) {
            throw new \InvalidArgumentException('non-nullable raw cannot be null');
        }
        $this->container['raw'] = $raw;

        return $this;
    }

    /**
     * Gets summary
     *
     * @return object|null
     */
    public function getSummary()
    {
        return $this->container['summary'];
    }

    /**
     * Sets summary
     *
     * @param object|null $summary 识别结果的统计摘要。
     *
     * @return self
     */
    public function setSummary($summary)
    {
        if (is_null($summary)) {
            throw new \InvalidArgumentException('non-nullable summary cannot be null');
        }
        $this->container['summary'] = $summary;

        return $this;
    }

    /**
     * Gets text
     *
     * @return string|null
     */
    public function getText()
    {
        return $this->container['text'];
    }

    /**
     * Sets text
     *
     * @param string|null $text 按阅读顺序拼接后的识别文本。
     *
     * @return self
     */
    public function setText($text)
    {
        if (is_null($text)) {
            throw new \InvalidArgumentException('non-nullable text cannot be null');
        }
        $this->container['text'] = $text;

        return $this;
    }

    /**
     * Gets timing
     *
     * @return object|null
     */
    public function getTiming()
    {
        return $this->container['timing'];
    }

    /**
     * Sets timing
     *
     * @param object|null $timing 耗时拆分信息，适合做性能统计或排查。
     *
     * @return self
     */
    public function setTiming($timing)
    {
        if (is_null($timing)) {
            throw new \InvalidArgumentException('non-nullable timing cannot be null');
        }
        $this->container['timing'] = $timing;

        return $this;
    }

    /**
     * Gets words_result
     *
     * @return \OpenAPI\Client\Model\PostImageOcr200ResponseWordsResultInner[]|null
     */
    public function getWordsResult()
    {
        return $this->container['words_result'];
    }

    /**
     * Sets words_result
     *
     * @param \OpenAPI\Client\Model\PostImageOcr200ResponseWordsResultInner[]|null $words_result 逐段文字结果。适合做高亮、框选和逐项解析。
     *
     * @return self
     */
    public function setWordsResult($words_result)
    {
        if (is_null($words_result)) {
            throw new \InvalidArgumentException('non-nullable words_result cannot be null');
        }
        $this->container['words_result'] = $words_result;

        return $this;
    }

    /**
     * Gets words_result_num
     *
     * @return int|null
     */
    public function getWordsResultNum()
    {
        return $this->container['words_result_num'];
    }

    /**
     * Sets words_result_num
     *
     * @param int|null $words_result_num 识别出的文字片段数量。
     *
     * @return self
     */
    public function setWordsResultNum($words_result_num)
    {
        if (is_null($words_result_num)) {
            throw new \InvalidArgumentException('non-nullable words_result_num cannot be null');
        }
        $this->container['words_result_num'] = $words_result_num;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


