<?php
/**
 * ImageApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ImageApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ImageApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getAvatarGravatar
     *
     * 获取Gravatar头像.
     *
     */
    public function testGetAvatarGravatar()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getImageBingDaily
     *
     * 获取必应每日壁纸.
     *
     */
    public function testGetImageBingDaily()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getImageMotou
     *
     * 生成摸摸头GIF (QQ号方式).
     *
     */
    public function testGetImageMotou()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getImageQrcode
     *
     * 动态生成二维码.
     *
     */
    public function testGetImageQrcode()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getImageTobase64
     *
     * 将在线图片转换为Base64.
     *
     */
    public function testGetImageTobase64()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postImageCompress
     *
     * 无损压缩图片.
     *
     */
    public function testPostImageCompress()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postImageFrombase64
     *
     * 通过Base64编码上传图片.
     *
     */
    public function testPostImageFrombase64()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postImageMotou
     *
     * 生成摸摸头GIF (图片上传或URL方式).
     *
     */
    public function testPostImageMotou()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postImageSpeechless
     *
     * 生成你们怎么不说话了表情包.
     *
     */
    public function testPostImageSpeechless()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postImageSvg
     *
     * SVG转图片.
     *
     */
    public function testPostImageSvg()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
